config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # You can have the root of your site routed with "root"
  root 'static_pages#index'
#        new_user_session GET    /users/sign_in(.:format)       devise/sessions#new
#            user_session POST   /users/sign_in(.:format)       devise/sessions#create
#    destroy_user_session DELETE /users/sign_out(.:format)      devise/sessions#destroy
#           user_password POST   /users/password(.:format)      devise/passwords#create
#       new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#      edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#                         PATCH  /users/password(.:format)      devise/passwords#update
#                         PUT    /users/password(.:format)      devise/passwords#update
#cancel_user_registration GET    /users/cancel(.:format)        devise/registrations#cancel
#       user_registration POST   /users(.:format)               devise/registrations#create
#   new_user_registration GET    /users/sign_up(.:format)       devise/registrations#new
#  edit_user_registration GET    /users/edit(.:format)          devise/registrations#edit
#                         PATCH  /users(.:format)               devise/registrations#update
#                         PUT    /users(_ .:format)             devise/registrations#update
#                         DELETE /users(.:format)               devise/registrations#destroy

  resources :posts
#     posts GET    /posts(.:format)          posts#index
#           POST   /posts(.:format)          posts#create
#  new_post GET    /posts/new(.:format)      posts#new
# edit_post GET    /posts/:id/edit(.:format) posts#edit
#      post GET    /posts/:id(.:format)      posts#show
#           PATCH  /posts/:id(.:format)      posts#update
#           PUT    /posts/:id(.:format)      posts#update
#           DELETE /posts/:id(.:format)      posts#destroy

  resources :comments
#     comments GET    /comments(.:format)          comments#index
#              POST   /comments(.:format)          comments#create
#  new_comment GET    /comments/new(.:format)      comments#new
# edit_comment GET    /comments/:id/edit(.:format) comments#edit
#      comment GET    /comments/:id(.:format)      comments#show
#              PATCH  /comments/:id(.:format)      comments#update
#              PUT    /comments/:id(.:format)      comments#update
#              DELETE /comments/:id(.:format)      comments#destroy

  resources :users, only: [:index, :show, :edit, :update]
# users GET    /users(.:format)               users#index
# user  GET    /users/:id(.:format)           users#show

  post 'post_votes/:id', to: 'post_votes#create'



  # resources :posts
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :title, :length => {:maximum => 140}, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :comments
  belongs_to :user

  has_many :post_votes
  URL_REGEX = /https?:\/\/[\S]+/

  validates :title, :length => {maximum: 140, minimum:1}, :presence => true
  validates :url, :length => {maximum: 2083, minimum:1}, :allow_blank => true, :format => {with: URL_REGEX}

  validate :span_free

  validate :only_twenty

  private
  def span_free
    if Post.count > 1
      last_post = Post.order(:created_at).last
      latest_time = last_post.created_at

      if latest_time > 1.minute.ago
        self.errors.add(:base, "Cannot post within 1 minute")
      end
    end
  end

  def only_twenty
    post_count = Post.count

    if post_count > 21
      self.errors.add(:base, "No more than 20 posts")
    end
  end
end

app/models/post_vote.rb
class PostVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  has_many :posts

  has_many :post_votes

  has_attached_file :avatar, :styles => { medium: "300x300>", thumb: "100x100>", default_url: "/images/cat.jpg"}
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  def index
    @comments = Comment.all
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.new(comment_params)
    user = {}
    user[:email] = @comment.user.email
    if @comment.save
      respond_to do |format|
        format.js {render 'create.js.erb'}
      end
    else
      flash[:message] = @comment.errors.messages
      respond_to do |format|
        format.js {render 'fail.js.erb'}
      end
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end

  private
    def comment_params
      params.require(:comment).permit(:title, :post_id)
    end
end

app/controllers/post_votes_controller.rb
class PostVotesController < ApplicationController
  def create
    post = Post.find(params[:id])
    new_vote = PostVote.new(:user => current_user, :post => post)
    if new_vote.save
      render json: new_vote, status: 201
    end
  end
end

app/controllers/posts_controller.rb
, class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def index
    @posts = Post.all
    @post = Post.new
  end

  def create
    # post = Post.new(title: params[:post][:title], url: params[:post][:url])
    puts "testing"
    puts post_params
    post = current_user.posts.new(post_params)
    if post.save
      redirect_to posts_path
    else
      flash[:message] = post.errors.messages
      redirect_to :back # render 'index'
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  private
  def post_params
    params.require(:post).permit(:title, :url)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if current_user.update(user_params)
      flash[:message] = "success"
      redirect_to edit_user_path
    else
      flash[:message] = "fail"
      redirect_to edit_user_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_votes_helper.rb
module PostVotesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.js.erb
var new_comment = "<%= raw escape_javascript(render :partial => 'posts/comment', :locals => {:comment => @comment}) %>";

$('#table-rows').append(new_comment);

$('#new_comment').trigger("reset");

$('#error-message').html("");

app/views/comments/fail.js.erb
$('#error-message').html("<%= @comment.errors.messages[:title][0] %>");
console.log("<%= @comment.errors.messages[:title][0] %>")

app/views/comments/index.html.erb
<h1>List of all comments</h1>

<% @comments.each do |comment| %>
  <%= link_to comment do %>
    <div>
      <%= comment.id %>
      <%= comment.title %>
      <%= comment.post_id %>
      <%= comment.created_at %>
    </div>
  <% end %>
<% end %>

<%= link_to "back", root_path %>

app/views/comments/show.html.erb
<div>
  <% c = @comment %>
  <%= c.title %>
  <%= c.post_id %>
</div>

<%= link_to "back", comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Basic Template</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <script type="text/javascript" src="https://code.jquery.com/ui/1.11.2/jquery-ui.min.js"></script>
  
  <%= csrf_meta_tags %>
</head>
<body class="vertical-center body-background">

<%= yield %>

</body>
</html>

app/views/posts/_comment.html.erb
<tr class="table-rows">
  <td class="active"><%= comment.id %></td>
  <td class="success"><%= comment.title %></td>
  <td class="warning"><%= comment.post_id %></td>
  <td class="info"><%= comment.created_at.to_date.to_s %></td>
  <td class="danger"><%= link_to "link", comment %></td>
  <td class="active"><%= comment.user.email %></td>
</tr>

app/views/posts/index.html.erb
<h1>List of all posts</h1>

<table class="table" data-toggle="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Url</th>
      <th>Time</th>
      <th>Link</th>
      <th>User Email</th>
    </tr>
    <% @posts.each do |post| %>
      <tr>
        <td class="active"><%= post.id %></td>
        <td class="success"><%= post.title %></td>
        <td class="warning"><%= post.url %></td>
        <td class="info"><%= post.created_at.to_date.to_s %></td>
        <td class="danger"><%= link_to "link", post %></td>
        <td class="active"><%= post.user.email %></td>
      </tr>
    <% end %>
  </thead>
</table>

<%= simple_form_for @post, :method => :post do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :url %>
  <%= f.text_field :url %>

  <%= f.submit "Submit" %>

<% end %>

<%= flash[:message] %>

app/views/posts/show.html.erb
<div>
  <%= @post.id %>
  <%= @post.title %>
  <%= @post.url %>
  <%= @post.user.email %>
  <%= @post.created_at %>
</div>

<%= button_to "Thumbs Up", "#", :id => "btn_vote", 'data-id' => @post.id %>
<h1 class="vote_count">
  <%= @post.post_votes.count %>
</h1>

<h1>Comments for post</h1>
<table class="table" data-toggle="table">
  <thead id="table-rows">
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Post ID</th>
      <th>Time</th>
      <th>Link</th>
      <th>User Email</th>
    </tr>
    <% @post.comments.each do |comment| %>
      <%= render :partial => 'posts/comment', :locals => {:comment => comment} %>
    <% end %>
  </thead>
</table>




<%= form_for @comment, :remote => true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  
  <%= f.text_field :post_id, :value => @post.id, :hidden => true %>

  <%= f.submit "Submit Comment", :class => "btn btn-success", :id => "btn_comment"%>
<% end %>

<div id="error-message"></div>

<%= link_to "back", posts_path %>

app/views/static_pages/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 text-center">
      <h1>HIHI</h1>
      <%= link_to "Post Page", posts_path %>
      <br>
      <%= link_to "Comment Page", comments_path %>
    </div>
    <%= current_user.to_json %>
    <%= current_user.to_yaml %>
    <% if current_user %>
      <%= button_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'btn btn-success' %>
    <% else %>
      <%= button_to "Sign in", new_user_session_path, :'data-id' => 'asdfasd', :class => 'btn btn-success' %>
      <%= button_to "Sign up", new_user_registration_path, :method => :get, :class => 'btn btn-warning' %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= image_tag asset_url('cat.jpg') %>
<%= asset_url('cat.jpg') %>

<div>
  <%= flash[:message] %> 
  <%= form_for @user, :html => { :multipart => true } do |form| %>
    <%= form.file_field :avatar %>
    <%= form.submit "Upload Picture" %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>List of Users</h1>
<% @users.each do |user| %>
  <div>
    <%= user.id %>
    <%= user.email %>
    <%= link_to "link", user %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.email %> profile</h1>
<h1>Post Created</h1>
<table class="table" data-toggle="table">
  <thead>
    <tr>
      <th>Post ID</th>
      <th>Title</th>
      <th>Time</th>
      <th>Link</th>
    </tr>
    <% @user.posts.each do |post| %>
      <tr>
        <td class="active"><%= post.id %></td>
        <td class="success"><%= post.title %></td>
        <td class="info"><%= post.created_at.to_date.to_s %></td>
        <td class="danger"><%= link_to "link", post %></td>
      </tr>
    <% end %>
  </thead>
</table>

<h1>Comments to posts</h1>
<table class="table" data-toggle="table">
  <thead>
    <tr>
      <th>Comment ID</th>
      <th>Title</th>
      <th>Post ID</th>
      <th>Time</th>
      <th>Link to Post</th>
    </tr>
    <% @user.comments.each do |comment| %>
      <tr>
        <td class="active"><%= comment.id %></td>
        <td class="success"><%= comment.title %></td>
        <td class="warning"><%= comment.post_id %></td>
        <td class="info"><%= comment.created_at.to_date.to_s %></td>
        <td class="danger"><%= link_to "link", comment.post %></td>
      </tr>
    <% end %>
  </thead>
</table>

<div>
  <%= link_to "edit profile", edit_user_path %>
</div>